# Generated by Django 3.2 on 2023-09-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
        ('users', '0005_auto_20230921_1852'),
    ]

    operations = [
    ]
