# Generated by Django 3.2 on 2023-09-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('reviews', '0003_auto_20230913_2118'),
        ('reviews', '0003_auto_20230914_0812'),
    ]

    operations = [
    ]
