# Generated by Django 3.2 on 2023-09-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20230920_2329'),
        ('reviews', '0008_alter_title_year'),
    ]

    operations = [
    ]
