# Generated by Django 3.2 on 2023-09-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_title_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'category', 'verbose_name': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'default_related_name': 'genre', 'verbose_name': 'Жанр'},
        ),
    ]
