# Generated by Django 3.2 on 2023-09-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20230922_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'category', 'ordering': ('name',), 'verbose_name': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'default_related_name': 'genre', 'ordering': ('name',), 'verbose_name': 'Жанр'},
        ),
    ]
